config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, path: 'devise_instructors', controllers: { registrations: 'instructors/registrations',
                                                                      sessions: 'instructors/sessions' }
  devise_for :admins, path: 'devise_admins', skip: [:registrations], controllers: { sessions: 'admins/sessions' }
  devise_for :users, path: 'devise_users', controllers: { registrations: 'users/registrations',
                                                          sessions: 'users/sessions' }

  resources :activities
  resources :instructors, only: [:index]
  resources :time_slots, except: [:update]
  resources :trainees

  unauthenticated :admin do
    unauthenticated :instructor do
      unauthenticated :user do
        root to: 'static_pages#home', as: :root
      end
      authenticated :user do
        root to: 'users#home', as: :user_root
        get '/purchase_tickets', to: 'users#purchase', as: :user_purchase
      end
    end
    authenticated :instructor do
      root to: 'instructors#home', as: :instructor_root
      get '/instructor/(:id)/salary', to: 'instructors#salary', as: :salary
      get '/instructor/(:id)/classes', to: 'instructors#my_classes', as: :my_classes
      get '/instructor/(:id)/instructor_edit_profile', to: 'instructors#instructor_edit_profile', as: :instructor_edit_profile
      patch 'instructor/(:id)/update', to: 'instructors#update', as: :update_instructor_profile
    end
  end

  authenticated :admin do
    root to: 'admins#dashboard', as: :admin_root

    scope '/enrollments' do
      get '/enroll', to: 'enrollments#enroll', as: :enroll
      get '/cancel', to: 'enrollments#cancel', as: :cancel_enrollment
      post '/finalize', to: 'enrollments#finalize', as: :finalize
      get '/enroll_child', to: 'enrollments#enroll_child', as: :enroll_child
      get '/enroll_via_slot', to: 'enrollments#enroll_via_slot', as: :enroll_via_slot
      patch '/finalize_for_slot', to: 'enrollments#finalize_for_slot', as: :finalize_for_slot
    end

    scope '/payments' do
      get '/index', to: 'payments#index', as: :payments_index
      patch '/pay', to: 'payments#pay', as: :payment
      get '/refund', to: 'payments#refund', as: :refund_payment
      get '/monthly_payment', to: 'payments#monthly_payment', as: :monthly_payment
    end

    scope '/management' do
      patch '/freeze', to: 'trainees#inactive', as: :freeze_trainee
    end

    post '/create_child', to: 'enrollments#create_child', as: :create_child
    get '/conversations/:id', to: 'admins#conversation', as: :conversation
    post '/conversations/log_new', to: 'admins#log_conversation', as: :log_conversation
    post '/tasks/add_task', to: 'admins#add_task', as: :add_task
    get '/tasks/closed', to: 'admins#closed_tasks', as: :closed_tasks
    patch '/tasks/update_status', to: 'admins#update_status', as: :update_status
    get '/calendar', to: 'admins#calendar', as: :calendar
    get '/instructors/edit/(:id)', to: 'instructors#edit', as: :edit_instructor
    patch '/instructors/(:id)/update', to: 'instructors#update', as: :update_instructor
    delete '/time_slots/destroy_slot_for/(:id)', to: 'time_slots#destroy_slots', as: :destroy_slots
    get '/time_slots/change_time_for/(:id)', to: 'time_slots#change_time', as: :change_slot_time
    patch '/time_slots/reschedule', to: 'time_slots#reschedule', as: :reschedule
    get 'enrollments/history/(:id)', to: 'enrollments#history', as: :enroll_history
    get '/activities/(:id)/contract/new_contract', to: 'contracts#new', as: :new_contract
    get '/activities/(:id)/contract/edit_contract', to: 'contracts#edit', as: :edit_contract
    post '/activities/(:id)/contracts/set_contract', to: 'contracts#set', as: :set_contract
    patch '/activities/(:id)/contracts/update_contract', to: 'contracts#update', as: :update_contract
    get '/all_salaries', to: 'admins#all_salaries', as: :all_salaries
    get '/time_slots/lock/(:id)', to: 'time_slots#lock', as: :lock_time_slot
  end

  get '/TBD', to: 'static_pages#placeholder', as: :placeholder
  get '/coming_soon', to: 'static_pages#coming_soon', as: :coming_soon
  get 'instructors/:id', to: 'instructors#show', as: :instructor
  get '/cancel_enroll', to: 'trainees#cancel_enroll', as: :cancel_enroll
end

app/views/admins/all_salaries.html.erb
<div class="basic-container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <table class="table table-hover table-bordered" style="background-color: white; border-collapseLcollapse;">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center"> שם המדריך </th>
                            <th class="text-center"> שם השיעור </th>
                            <th class="text-center"> מספר שיעורים החודש </th>
                            <th class="text-center"> משתתפים </th>
                            <th class="text-center"> תשלום כולל </th>
                            <th class="text-center"> (לחץ לצפייה בפירוט השיעורים) </th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @activities.each_with_index do |activity, index1| %>
                        <% target = "extra" + index1.to_s %>
                        <% monthly_hash = activity.monthly_data(@month) %>
                        <tr data-toggle="collapse" data-target=<%= "." + target %> style="font-weight: bold; color: black; background-color: <%= activity.instructor.color %>;">
                            <td><%= activity.instructor.full_name %></td>
                            <td><%= activity.name %></td>
                            <td><%= monthly_hash[:slots_arr].count %></td>
                            <td><%= monthly_hash[:trainees_avg].round(2) %> (ממוצע)</td>
                            <td> <%= monthly_hash[:payment][:total] %> </td>
                            <td> <span class="glyphicon glyphicon-plus"></span> </td>
                        </tr>
                        <% monthly_hash[:slots_arr].each_with_index do |slot, index2| %>
                        <tr>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= index2 %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= slot.start_time.strftime("%d/%m/%y") %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= slot.trainees.count %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= monthly_hash[:payment][slot.id] %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>">
                                    <% slot.trainees.each do |trainee| %>
                                    <%= trainee.full_name + ' | ' %>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <%= render 'layouts/salary_months', activities: @activities %>
    </div>
</div>

app/views/admins/calendar.html.erb
<div class="basic-container">
    <%= month_calendar(events: @activities) do |date, activities| %>
    <%= date %>

    <% activities.each do |activity| %>
    <% enrolled_color = "white" %>

    <%= render 'layouts/activity_card', activity: activity, enrolled_color: enrolled_color %>

    <% end %>
    <% end %>

</div>

app/views/admins/closed_tasks.html.erb
<% provide(:title, "Instructor Profile") %>


<div class="basic-container">

    <%= image_tag @activity.displayed_image,
                     loading: "lazy", alt: @activity.name, class: "img-circle img-fluid" %>

    <div class="profile-stats">
        <ul class="no-bullets">
            <h4>
                <li class="menu-item"> <%= @activity.name %> </li>
            </h4>
            <h4>
                <li class="menu-item"> <%=link_to @activity.instructor.first + ' ' + @activity.instructor.last, @activity.instructor %> </li>
            </h4>
            <h4>
                <li class="menu-item">משך השיעור | <%= @activity.duration %> דקות</li>
            </h4>
            <li class="menu-item"> <%=simple_format(@activity.description) %> </li>

app/views/admins/conversation.html.erb
<div class="basic-container">
    <div class="row">
        <aside class="col-md-3">
            <section>
                <%= image_tag 'default_profile.jpg' , loading: "lazy" , alt: @trainee.first, class: "rounded-full" %>
            </section>
            <section class="name">
                <%= @trainee.first.capitalize %>
                    <%= @trainee.last.capitalize %>
            </section>
        </aside>

        <div class="col-md-8">
            <div class="profile-stats">
                <ul class="no-bullets">
                    <li class="menu-item">דואר אלקטרוני | <%= @trainee.email %>
                    </li>
                    <li class="menu-item">מספר טלפון | <%= @trainee.phone %>
                    </li>
                    <li class="menu-item">
                        <%= link_to "חזרה לפרופיל" , trainee_path(@trainee), class: "btn btn-primary" %>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="profile-stats">
            <h3 style=" margin-top: 5px;">
                משימות פתוחות
                <%= link_to "משימות סגורות" , closed_tasks_path(id: @trainee.id), class: "btn btn-primary" %>
            </h3>
            <div class="basic-container">

                <%= bootstrap_form_for(@task, url: add_task_path, local: true) do |f| %>
                    <%= f.date_field :due_date, label: "תאריך סיום" %>
                        <%= f.text_area :content, label: "משימה" %>
                            <%= f.hidden_field :trainee_id, value: @trainee.id %>
                                <%= f.submit "צור משימה" , class: "btn btn-primary" %>
                                    <% end %>
            </div>
            <% if @task_logs.empty? %>
                <h3>
                    אין משימות פתוחות
                </h3>
                <% else %>
                    <div class="table-responsive" style="direction: rtl;">
                        <table class="table table-hover table-bordered" style="background-color: white;">
                            <thead class="thead-dark" style="color: black; ">
                                <tr>
                                    <th class="text-center"> משימה </th>
                                    <th class="text-center">תאריך פתיחה </th>
                                    <th class="text-center">דדליין </th>
                                    <th colspan="1"></th>
                                </tr>
                            </thead>

                            <tbody style="color: black;">
                                <% @task_logs.each do |log| %>
                                    <tr>
                                        <td>
                                            <%= simple_format(log.content) %>
                                        </td>
                                        <td>
                                            <%= log.created_at.strftime("%d.%m.%y") %>
                                        </td>
                                        <td>
                                            <%= log.due_date.strftime("%d.%m.%y") %>
                                        </td>
                                        <td>
                                            <%= bootstrap_form_for(log, url: update_status_path, local: true) do |f| %>
                                                <%= f.hidden_field :id, value: log.id %>
                                                    <%= f.hidden_field :trainee_id, value: @trainee.id %>
                                                        <%= f.submit "סגירת משימה" , class: "btn btn-primary" %>
                                        </td>

                                        <% end %>

                                    </tr>
                                    <% end %>
                            </tbody>
                        </table>
                    </div>
                    <% end %>
        </div>
    </div>

    <div class="row">

        <div class="profile-stats">
            <h3 style=" margin-top: 5px;">
                יומן שיחות
            </h3>
            <div class="basic-container">

                <%= bootstrap_form_for(@log, url: log_conversation_path, local: true) do |f| %>

                    <%= f.text_area :content, label: "תוכן השיחה" %>
                        <%= f.hidden_field :trainee_id, value: @trainee.id %>
                            <%= f.submit "הזן שיחה" , class: "btn btn-primary" %>
                                <% end %>
            </div>
            <% if @conversation_logs.nil? %>
                <h3>
                    לא קיימות רשומות של שיחות עבור לקוח זה
                </h3>
                <% else %>
                    <div class="table-responsive" style="direction: rtl;">
                        <table class="table table-hover table-bordered" style="background-color: white;">
                            <thead class="thead-dark" style="color: black;">
                                <tr>
                                    <th class="text-center">תאריך השיחה </th>
                                    <th class="text-center">תוכן השיחה </th>
                                </tr>
                            </thead>

                            <tbody style="color: black;">
                                <% @conversation_logs.each do |log| %>
                                    <tr>
                                        <td>
                                            <%= log.created_at.strftime("%d.%m.%y") %>
                                        </td>
                                        <td>
                                            <%= simple_format(log.content) %>
                                        </td>
                                    </tr>
                                    <% end %>
                                        <% end %>
                            </tbody>
                        </table>
                    </div>
        </div>
    </div>



</div>
</div>

app/views/admins/dashboard.html.erb
<div class="basic-container">
    <h2>
      סגירת שיעורים קודמים
    </h2>
    <% if @past_unlocked_slots.empty? %>
    <h3>
      הכל מעודכן, כל הכבוד
    </h3>
    <% else %>
    <div class="row">
      <div class="col-md-12">
        <div class="panel-body">
          <table class="table table-hover table-bordered" style="background-color: white; border-collapse: collapse;">
            <thead class="thead-dark">
            <tr>
              <th class="text-center"> שם השיעור </th>
              <th class="text-center"> תאריך השיעור </th>
              <th class="text-center"> שם המדריך </th>
              <th class="text-center"> פעולות </th>
            </tr>
            </thead>

            <tbody>
            <% @past_unlocked_slots.each_with_index do |activity, index1| %>
              <% target = "extra" + index1.to_s %>
              <tr style=<%= 'font-weight: bold; color: black; background-color:' + activity.mother.instructor.color + ';' %>>
              <td><%= activity.mother.name %></td>
              <td><%= activity.start_time.strftime("%d/%m/%y") %></td>
              <td><%= activity.mother.instructor.full_name %></td>
              <td >
                <span class="btn btn-primary btn-m">
                  <i class="fas fa-plus" data-bs-toggle="collapse" data-bs-target=<%= "." + target %>> פירוט מתאמנים </i>
                  </span>
                |
                <%= link_to 'נעילת שיעור', lock_time_slot_path(id: activity.id),
                                                                              class: "btn btn-primary btn-m" %>
              </td>
              </tr>
              <% activity.trainees.each_with_index do |trainee, index2| %>
                <tr>
                  <td class="hiddenRow">
                    <div class="collapse <%= target %>"><%= index2 %></div>
                  </td>
                  <td class="hiddenRow">
                    <div class="collapse <%= target %>"><%= trainee.full_name %></div>
                  </td>
                  <td class="hiddenRow">
                    <div class="collapse <%= target %>">TBD - payment type</div>
                  </td>
                  <td class="hiddenRow">
                    <div class="collapse <%= target %>">
                      <%= link_to 'בטל רישום', cancel_enrollment_path(trainee_id: trainee.id, slot_id: activity.id),
                                  class: "btn btn-primary btn-sm" %>
                    </div>
                  </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<div class="basic-container">
  <h2>
    השיעורים של היום
  </h2>
  <div class="accordion" id="accordionExample">
    <% @today_slots.each_with_index  do |slot, index| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id=<%= 'heading' + index.to_s %>>
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target=<%= '#collapse'+index.to_s %> aria-controls=<% '#collapse'+index.to_s %>>
            <%= slot.mother.name + ' בשעה ' + slot.start_time.strftime("%H:%M") + ' עם ' + slot.mother.instructor.full_name %>
          </button>
        </h2>
      </div>
      <div class="accordion-collapse collapse" aria-labelledby=<%= 'heading' + index.to_s %> data-bs-parent="#accordionExample" id= <%= 'collapse'+index.to_s %>>
        <div class="accordion-body">
          <div class="row">
            <aside class="col col-md-4">
              <section class="profile-stats">
                  <ul class="no-bullets">
                    <% slot.trainees.each do |trainee| %>
                    <li>
                      <%= link_to trainee.full_name, trainee, class: 'btn btn-primary btn-md' %>
                    </li>
                    <% end %>
                  </ul>
              </section>
            </aside>
            <div class="col col-md-8">
              <div style="background-color: white; margin: 0 auto">
                <% a = TimeSlot.graph_slots(slot)  %>
              <%= line_chart TimeSlot.graph_slots(slot).collect{|s| [s[:start_time], s.trainees.count]} %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

<div class="basic-container">
    <%= render 'layouts/calendar' , activities: @activities, week_number: 1, date_begin: @start_date, show_toggle_button:
        true, show_date: true %>
</div>

app/views/admins/dashboard.js.erb
$("#events_calendar").html("<%= escape_javascript render ('layouts/calendar', activities: @activities, week_number: 1, date_begin: Date.today.beginning_of_week, show_toggle_button: true) %>");

app/views/admins/enroll.html.erb
<div class="basic-container">

    <%= bootstrap_form_with(model: @time_slot, url: finalize_path, local: true, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-10") do |f| %>
    <%= f.hidden_field :id, value: @time_slot.id, class: "btn btn-primary" %>
    <%= f.select :enrolled, @full_names_arr, {}, class: 'js-activities', label: "" %>
    <%= f.submit "הרשמה לשיעור" %>
    <% end %>

</div>