config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, path: 'devise_instructors', controllers: { registrations: 'instructors/registrations',
                                                                      sessions: 'instructors/sessions' }
  devise_for :admins, path: 'devise_admins', skip: [:registrations], controllers: { sessions: 'admins/sessions' }
  devise_for :users, path: 'devise_users', controllers: { registrations: 'users/registrations',
                                                          sessions: 'users/sessions' }

  resources :activities
  resources :instructors, only: [:index]
  resources :time_slots, except: [:update]
  resources :trainees

  unauthenticated :admin do
    unauthenticated :instructor do
      unauthenticated :user do
        root to: 'static_pages#home', as: :root
      end
      authenticated :user do
        root to: 'users#home', as: :user_root
        get '/purchase_tickets', to: 'users#purchase', as: :user_purchase
      end
    end
    authenticated :instructor do
      root to: 'instructors#home', as: :instructor_root
      get '/instructor/(:id)/salary', to: 'instructors#salary', as: :salary
      get '/instructor/(:id)/classes', to: 'instructors#my_classes', as: :my_classes
      get '/instructor/(:id)/instructor_edit_profile', to: 'instructors#instructor_edit_profile', as: :instructor_edit_profile
      patch 'instructor/(:id)/update', to: 'instructors#update', as: :update_instructor_profile
    end
  end

  authenticated :admin do
    root to: 'admins#dashboard', as: :admin_root

    scope '/enrollments' do
      get '/enroll', to: 'enrollments#enroll', as: :enroll
      get '/cancel', to: 'enrollments#cancel', as: :cancel_enrollment
      post '/finalize', to: 'enrollments#finalize', as: :finalize
      get '/enroll_child', to: 'enrollments#enroll_child', as: :enroll_child
      get '/enroll_via_slot', to: 'enrollments#enroll_via_slot', as: :enroll_via_slot
      patch '/finalize_for_slot', to: 'enrollments#finalize_for_slot', as: :finalize_for_slot
    end

    scope '/payments' do
      get '/index', to: 'payments#index', as: :payments_index
      patch '/pay', to: 'payments#pay', as: :payment
      get '/refund', to: 'payments#refund', as: :refund_payment
      get '/monthly_payment', to: 'payments#monthly_payment', as: :monthly_payment
    end

    scope '/management' do
      patch '/freeze', to: 'trainees#inactive', as: :freeze_trainee
    end

    post '/create_child', to: 'enrollments#create_child', as: :create_child
    get '/conversations/:id', to: 'admins#conversation', as: :conversation
    post '/conversations/log_new', to: 'admins#log_conversation', as: :log_conversation
    post '/tasks/add_task', to: 'admins#add_task', as: :add_task
    get '/tasks/closed', to: 'admins#closed_tasks', as: :closed_tasks
    patch '/tasks/update_status', to: 'admins#update_status', as: :update_status
    get '/calendar', to: 'admins#calendar', as: :calendar
    get '/instructors/edit/(:id)', to: 'instructors#edit', as: :edit_instructor
    patch '/instructors/(:id)/update', to: 'instructors#update', as: :update_instructor
    delete '/time_slots/destroy_slot_for/(:id)', to: 'time_slots#destroy_slots', as: :destroy_slots
    get '/time_slots/change_time_for/(:id)', to: 'time_slots#change_time', as: :change_slot_time
    patch '/time_slots/reschedule', to: 'time_slots#reschedule', as: :reschedule
    get 'enrollments/history/(:id)', to: 'enrollments#history', as: :enroll_history
    get '/activities/(:id)/contract/new_contract', to: 'contracts#new', as: :new_contract
    get '/activities/(:id)/contract/edit_contract', to: 'contracts#edit', as: :edit_contract
    post '/activities/(:id)/contracts/set_contract', to: 'contracts#set', as: :set_contract
    patch '/activities/(:id)/contracts/update_contract', to: 'contracts#update', as: :update_contract
    get '/all_salaries', to: 'admins#all_salaries', as: :all_salaries
    get '/time_slots/lock/(:id)', to: 'time_slots#lock', as: :lock_time_slot
  end

  get '/TBD', to: 'static_pages#placeholder', as: :placeholder
  get '/coming_soon', to: 'static_pages#coming_soon', as: :coming_soon
  get 'instructors/:id', to: 'instructors#show', as: :instructor
  get '/cancel_enroll', to: 'trainees#cancel_enroll', as: :cancel_enroll
end

app/models/instructor.rb
class Instructor < ApplicationRecord

  has_many :activities, dependent: :destroy
  has_many :time_slots, through: :activities
  has_many :notifications, dependent: :destroy
  has_one_attached :image
  has_one_attached :logo


  def displayed_image
    if image.attached?
      image.variant(resize_to_fit: [290, 350])
    else
      'default_profile.jpg'
    end
  end

  def displayed_logo
    if logo.attached?
      logo.variant(resize_to_fit: [120, 120])
    else
      'default_profile.jpg'
    end
  end

  def full_name
    self.first.capitalize + ' ' + self.last.capitalize
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/instructors/confirmations_controller.rb
# frozen_string_literal: true

class Instructors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/instructors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Instructors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/instructors/passwords_controller.rb
# frozen_string_literal: true

class Instructors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/instructors/registrations_controller.rb
# frozen_string_literal: true

class Instructors::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_admin!, only: [:new, :create, :destroy, :edit]
  
  before_action :configure_sign_up_params, only: [:create]

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        @new_instructor = resource
        redirect_to admin_root_path
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
     super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:image, :color, :logo])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/instructors/sessions_controller.rb
# frozen_string_literal: true

class Instructors::SessionsController < Devise::SessionsController
  

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/instructors/unlocks_controller.rb
# frozen_string_literal: true

class Instructors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController



  def home
  end
  
  def show
    @instructor = Instructor.find(params[:id])
    @instructor_time_slots = TimeSlot.joins(:activity => :instructor).where(:instructor => {:id => @instructor.id},
                                :start_time => (Date.today..Date.today + 2.week)).order(start_time: :desc)
  end


  def index
    @all_instructors = Instructor.all
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def instructor_edit_profile
    @instructor = Instructor.find(params[:id])
  end

  def update
    Instructor.update(update_params)
    redirect_to instructors_path
  end

  def salary
    if params[:view_month].nil? then @month = Date.today.month else @month = params[:view_month] end
    @activities = current_instructor.activities
  end
  

  private
  def update_params
    params.require(:instructor).permit(:email, :first, :last, :phone, :description, :speciality, :color, :image, :logo)
  end
  
  
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/edit.html.erb
<div class="basic-container">
    <div class="col"></div>
    <div class="col-10">
        <h2>עדכן מדריכ/ה</h2><br>
        <%= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name), local: true, layout:
            :horizontal ) do |f| %>
            <%= render "instructors/shared/error_messages" , resource: resource %>



                <%= f.email_field :email, label: "אימייל" , autofocus: true, required: true %><br>
                    <%= f.text_field :first, label: "שם פרטי" , required: true %><br>
                        <%= f.text_field :last, label: "שם משפחה" , required: true %><br>
                            <%= f.telephone_field :phone, label: "מספר טלפון" , required: true %><br>
                                <%= f.text_field :exp, label: "שנות ניסיון" , required: true %><br>
                                    <%= f.text_field :speciality, label: "התמחות" , required: true %><br>
                                        <%= f.text_area :description, label: "תיאור" , required: true %><br>
                                            <%= f.color_field :color, label: "בחר צבע לשיעור" , required: true %><br>
                                                <%= f.file_field :image, label: "העלה תמונת פרופיל" %><br>
                                                    <%= f.file_field :logo, label: "לוגו שיעור (אם יש)" %><br>
                                                        <%= f.password_field :password, label: "ססמה" , required: true
                                                            %><br>
                                                            <%= f.password_field :password_confirmation,
                                                                label: "הקש ססמה פעם שנייה" , required: true %><br>
                                                                <div class="row">
                                                                    <div>
                                                                        <%= f.submit "עדכן מדריכ/ה" %>
                                                                            <br>
                                                                    </div>
                                                                    <br />
                                                                </div>




                                                                <% end %>

    </div>
    <div class="col"></div>
</div>

app/views/instructors/home.html.erb
<% provide(:title, "Instructor Dashboard") %>


<div class="basic-container">
    <div class="row">
        <h4 style="color: black; text-align: center;">
            <strong> השיעורים של <%= current_instructor.first %> </strong>
        </h4>
        <%= render 'layouts/admin_calendar', activities: current_instructor.time_slots, show_toggle_button: true, show_date: true, week_number: 1, date_begin: Date.today.beginning_of_week %>

    </div>
</div>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="basic-container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <table class="table table-hover table-bordered" style="background-color: white;">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">First Name</th>
                            <th class="text-center">Last Name</th>
                            <th class="text-center">Speciality</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @all_instructors.each do |instructor| %>
                        <tr>
                            <td><%= instructor.first %></td>
                            <td><%= instructor.last %></td>
                            <td><%= instructor.speciality %></td>

                            <td><%= link_to 'Show', instructor %></td>
                            <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
                            <td><%= link_to 'Destroy', registration_path(instructor), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br>

app/views/instructors/instructor_edit_profile.html.erb
<% provide(:title, "Instructor Profile") %>
<div class="basic-container">
    <div class="row">
        <aside class="col-md-3">
            <div style="background-color: transparent; display: block; text-align: center; margin-top: 5px;">

                <%= image_tag @instructor.displayed_image,
                     loading: "lazy", alt: @instructor.first, class: "rounded-full", style: "border-radius: 10%" %>
            </div>
            <section class="mini-form">
                <%= bootstrap_form_for(@instructor, url: update_instructor_profile_path, local: true) do |f| %>
                <%= f.file_field :image %>
                <%= f.hidden_field :id, value: @instructor.id %>
                <%= f.submit "עדכן תמונה", class: "btn btn-primary" %>
                <% end %>
            </section>
            <section class="name">
                <%= @instructor.first.capitalize %> <%= @instructor.last.capitalize %>
            </section>
        </aside>

        <div class="col-md-8">
            <div class="profile-stats">

                <%= image_tag @instructor.displayed_logo, loading: "lazy", class: "img-circle img-fluid" %>
                <div class="mini-form">
                    <%= bootstrap_form_for(@instructor, url: update_instructor_profile_path, local: true) do |f| %>
                    <%= f.file_field :logo %>
                    <%= f.hidden_field :id, value: @instructor.id %>
                    <%= f.submit "עדכן לוגו", class: "btn btn-primary" %>
                    <% end %>
                </div>
                <ul class="no-bullets">
                    <h4>
                        <li class="menu-item"> <strong><%= @instructor.speciality %></strong> </li>
                    </h4>
                    <%= simple_format(@instructor.description) %>
                    <div class="mini-form">
                        <%= bootstrap_form_for(@instructor, url: update_instructor_profile_path, local: true) do |f| %>
                        <%= f.text_area :description %>
                        <%= f.hidden_field :id, value: @instructor.id %>
                        <%= f.submit "עדכן תיאור", class: "btn btn-primary" %>
                        <% end %>
                    </div>
                </ul>
            </div>
        </div>
    </div>

</div>

app/views/instructors/salary.html.erb
<div class="basic-container">

    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <table class="table table-hover table-bordered" style="background-color: white; border-collapseLcollapse;">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center"> שם השיעור </th>
                            <th class="text-center"> מספר שיעורים החודש </th>
                            <th class="text-center"> משתתפים </th>
                            <th class="text-center"> תשלום כולל </th>
                            <th class="text-center"> (לחץ לצפייה בפירוט השיעורים) </th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @activities.each_with_index do |activity, index1| %>
                        <% target = "extra" + index1.to_s %>
                        <% monthly_hash = activity.monthly_data(@month) %>
                        <tr data-toggle="collapse" data-target=<%= "." + target %> style="background-color: grey;">
                            <td><%= activity.name %></td>
                            <td><%= monthly_hash[:slots_arr].count %></td>
                            <td><%= monthly_hash[:trainees_avg].round(2) %> (ממוצע)</td>
                            <td> <%= monthly_hash[:payment][:total] %> </td>
                            <td> <span class="glyphicon glyphicon-plus"></span> </td>
                        </tr>
                        <% monthly_hash[:slots_arr].each_with_index do |slot, index2| %>
                        <tr>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= index2 %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= slot.start_time.strftime("%d/%m/%y") %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= slot.trainees.count %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>"><%= monthly_hash[:payment][slot.id] %></div>
                            </td>
                            <td class="hiddenRow">
                                <div class="collapse <%= target %>">
                                    <% slot.trainees.each do |trainee| %>
                                    <%= trainee.full_name + ' | ' %>
                                    <% end %>
                                </div>
                            </td>
                        </tr>
                        <% end %>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <%= render 'layouts/salary_months', activities: @activities %>
    </div>
</div>

app/views/instructors/show.html.erb
<% provide(:title, "Instructor Profile" ) %>
    <div class="basic-container">
        <div class="row">
            <aside class="col-md-3">
                <div style="background-color: transparent; display: block; text-align: center; margin-top: 5px;">

                    <%= image_pack_tag @instructor.displayed_image, loading: "lazy" , alt: @instructor.first,
                        class: "rounded-full" , style: "border-radius: 10%" %>
                </div>
                <section class="name">
                    <%= @instructor.first.capitalize %>
                        <%= @instructor.last.capitalize %>
                </section>
            </aside>

            <div class="col-md-8">
                <div class="profile-stats">
                    <% if @instructor.activities.exists? %>
                        <%= image_pack_tag @instructor.displayed_logo, loading: "lazy" , alt:
                            @instructor.activities.first.name, class: "img-circle img-fluid" %>
                            <% end %>
                                <ul class="no-bullets">
                                    <h4>
                                        <li class="menu-item"> <strong>
                                                <%= @instructor.speciality %>
                                            </strong> </li>
                                    </h4>
                                    <%= simple_format(@instructor.description) %>

                                </ul>
                </div>


                <div class="profile-stats" style="background-color: transparent !important;">


                    <div style="display: block;">
                        <% if admin_signed_in? %>
                            <%= link_to "הוסף פעילות" , new_activity_path(id: @instructor.id),
                                class: "btn btn-primary btn-lg" %>
                                <% else %>
                                    <%= link_to "חזרה לעמוד הבית" , root_path, class: "btn btn-primary btn-lg" %>
                                        <% end %>
                    </div>
                </div>
            </div>



        </div>
        <div class="row">
            <h4 style="color: black; text-align: center;">
                <strong> השיעורים של <%= @instructor.first %> </strong>
            </h4>
            <%= render 'layouts/calendar' , activities: @instructor.time_slots, show_toggle_button: false, show_date:
                false, week_number: 1, date_begin: Date.today.beginning_of_week %>

        </div>
    </div>