config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :instructors, path: 'devise_instructors', controllers: { registrations: 'instructors/registrations',
                                                                      sessions: 'instructors/sessions' }
  devise_for :admins, path: 'devise_admins', skip: [:registrations], controllers: { sessions: 'admins/sessions' }
  devise_for :users, path: 'devise_users', controllers: { registrations: 'users/registrations',
                                                          sessions: 'users/sessions' }

  resources :activities
  resources :instructors, only: [:index]
  resources :time_slots, except: [:update]
  resources :trainees

  unauthenticated :admin do
    unauthenticated :instructor do
      unauthenticated :user do
        root to: 'static_pages#home', as: :root
      end
      authenticated :user do
        root to: 'users#home', as: :user_root
        get '/purchase_tickets', to: 'users#purchase', as: :user_purchase
      end
    end
    authenticated :instructor do
      root to: 'instructors#home', as: :instructor_root
      get '/instructor/(:id)/salary', to: 'instructors#salary', as: :salary
      get '/instructor/(:id)/classes', to: 'instructors#my_classes', as: :my_classes
      get '/instructor/(:id)/instructor_edit_profile', to: 'instructors#instructor_edit_profile', as: :instructor_edit_profile
      patch 'instructor/(:id)/update', to: 'instructors#update', as: :update_instructor_profile
    end
  end

  authenticated :admin do
    root to: 'admins#dashboard', as: :admin_root

    scope '/enrollments' do
      get '/enroll', to: 'enrollments#enroll', as: :enroll
      get '/cancel', to: 'enrollments#cancel', as: :cancel_enrollment
      post '/finalize', to: 'enrollments#finalize', as: :finalize
      get '/enroll_child', to: 'enrollments#enroll_child', as: :enroll_child
      get '/enroll_via_slot', to: 'enrollments#enroll_via_slot', as: :enroll_via_slot
      patch '/finalize_for_slot', to: 'enrollments#finalize_for_slot', as: :finalize_for_slot
    end

    scope '/payments' do
      get '/index', to: 'payments#index', as: :payments_index
      patch '/pay', to: 'payments#pay', as: :payment
      get '/refund', to: 'payments#refund', as: :refund_payment
      get '/monthly_payment', to: 'payments#monthly_payment', as: :monthly_payment
    end

    scope '/management' do
      patch '/freeze', to: 'trainees#inactive', as: :freeze_trainee
    end

    post '/create_child', to: 'enrollments#create_child', as: :create_child
    get '/conversations/:id', to: 'admins#conversation', as: :conversation
    post '/conversations/log_new', to: 'admins#log_conversation', as: :log_conversation
    post '/tasks/add_task', to: 'admins#add_task', as: :add_task
    get '/tasks/closed', to: 'admins#closed_tasks', as: :closed_tasks
    patch '/tasks/update_status', to: 'admins#update_status', as: :update_status
    get '/calendar', to: 'admins#calendar', as: :calendar
    get '/instructors/edit/(:id)', to: 'instructors#edit', as: :edit_instructor
    patch '/instructors/(:id)/update', to: 'instructors#update', as: :update_instructor
    delete '/time_slots/destroy_slot_for/(:id)', to: 'time_slots#destroy_slots', as: :destroy_slots
    get '/time_slots/change_time_for/(:id)', to: 'time_slots#change_time', as: :change_slot_time
    patch '/time_slots/reschedule', to: 'time_slots#reschedule', as: :reschedule
    get 'enrollments/history/(:id)', to: 'enrollments#history', as: :enroll_history
    get '/activities/(:id)/contract/new_contract', to: 'contracts#new', as: :new_contract
    get '/activities/(:id)/contract/edit_contract', to: 'contracts#edit', as: :edit_contract
    post '/activities/(:id)/contracts/set_contract', to: 'contracts#set', as: :set_contract
    patch '/activities/(:id)/contracts/update_contract', to: 'contracts#update', as: :update_contract
    get '/all_salaries', to: 'admins#all_salaries', as: :all_salaries
    get '/time_slots/lock/(:id)', to: 'time_slots#lock', as: :lock_time_slot
  end

  get '/TBD', to: 'static_pages#placeholder', as: :placeholder
  get '/coming_soon', to: 'static_pages#coming_soon', as: :coming_soon
  get 'instructors/:id', to: 'instructors#show', as: :instructor
  get '/cancel_enroll', to: 'trainees#cancel_enroll', as: :cancel_enroll
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :instructor
  has_many :time_slots, dependent: :destroy
  has_one :contract, dependent: :destroy


  enum contract_type: [:undefined, :hourly, :per_head, :gradient]



  def monthly_data(month)
    slots_in_month = self.locked_time_slots.select {|x| x.start_time.month == month.to_i }
    total_trainees = 0
    slots_in_month.each do |slot|
      total_trainees += slot.trainees.count
    end
    if slots_in_month.count != 0 then avg = total_trainees/slots_in_month.count.to_f else avg = 0 end
    payment_hash = self.contract_if_exists.calc_payout(slots_in_month)
    return {slots_arr: slots_in_month, trainees_avg: avg, payment: payment_hash}
  end

  def payment_hash
    current_month = Date.today.month
    if self.contract_if_exists.rate_type == 'monthly'
        trainee_ids = self.time_slots.first.trainee_ids
        trainee_status_hash = MonthlyPayment.status(current_month, trainee_ids, self.id)
        return trainee_status_hash
    end
  end

  def contract_if_exists
    if self.contract.nil?
      return Contract.new(activity_id: self.id, rate: 1, rate_type: "undefined")
    else
      return self.contract
    end
  end

  def locked_time_slots
    slots = self.time_slots.select {|x| x.locked }
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end


  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @time_slots = @activity.time_slots.where(start_time: Date.today.beginning_of_week..Date.today.beginning_of_week + 7.day, activity_id: params[:id]).order(start_time: :asc)
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @instructor = Instructor.find(params[:id])
  end

  # GET /activities/1/edit
  def edit
    @instructor = Activity.find(params[:id]).instructor
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to new_time_slot_path(id: @activity.id), notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:instructor_id, :name, :duration, :start_time, :end_time, :capacity, :reccuring, :description, :image)
    end
end

app/views/activities/_form.html.erb
<h1>
    New Activity for <%= @instructor.first %> <%= @instructor.last %>
</h1>

<%= bootstrap_form_with(model: activity, local: true, layout: :horizontal, label_col: "col-sm-4", control_col: "col-sm-10") do |f| %>
<% if activity.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

    <ul>
        <% activity.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="row">
    <div class="container-fluid rounded p-3 my-3 text-white" , style="background-color: transparent;">
        <div class="col-md-10 col-md-offset-2">
            <%= f.text_field :instructor_id, value: @instructor.id %>
            <%= f.text_field :name, label: "Name", autofocus: true, required: true %>
            <%= f.number_field :duration, label: "Duration", required: true %>
            <%= f.text_field :capacity, label: "Max. Capacity", required: true %>
            <%= f.text_area :description, label: "Description"%>

            <div class="row" , style="align: center">
                <div>
                    <%= f.submit "Create New Activity" %><br>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/activities/edit.html.erb
<div class="basic-container">

    <h1>Editing Activity</h1>

    <%= render 'form', activity: @activity %>

    <%= link_to 'Show', @activity %> |
    <%= link_to 'Back', activities_path %>

</div>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="basic-container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <table class="table table-hover table-bordered" style="background-color: white">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">Instructor</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Duration</th>
                            <th class="text-center">Capacity</th>
                            <th colspan="4"></th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @activities.each do |activity| %>
                        <tr>
                            <td><%= activity.instructor.first %> <%= activity.instructor.last %></td>
                            <td><%= activity.name %></td>
                            <td><%= activity.duration %></td>
                            <td><%= activity.capacity %></td>
                            <td><%= link_to 'Show', activity %></td>
                            <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
                            <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br>

app/views/activities/new.html.erb
<div class="basic-container" , style="max-width: 700px;">
    <div class="container-fluid rounded p-3 my-3 text-white" , style="background-color: transparent; margin-top: 20px;">
        <div class="col-md-10 col-md-offset-2">

            <%= render 'form', activity: @activity %>

            <%= link_to 'Back', activities_path %>
        </div>
    </div>
</div>

app/views/activities/show.html.erb
<% provide(:title, "Instructor Profile" ) %>


    <div class="basic-container">

        <%= image_pack_tag @activity.instructor.displayed_logo, loading: "lazy" , alt: @activity.name,
            class: "img-circle img-fluid" %>

            <div class="profile-stats">
                <ul class="no-bullets">
                    <h4>
                        <li class="menu-item">
                            <%= @activity.name %>
                        </li>
                    </h4>
                    <h4>
                        <li class="menu-item">
                            <%=link_to @activity.instructor.first + ' ' + @activity.instructor.last,
                                @activity.instructor %>
                        </li>
                    </h4>
                    <h4>
                        <li class="menu-item">משך השיעור | <%= @activity.duration %> דקות</li>
                    </h4>
                    <li class="menu-item">
                        <%=simple_format(@activity.description) %>
                    </li>

                </ul>
                <h4>
                    השיעורים הקרובים
                </h4>
                <div class="table-responsive" style="direction: rtl;">
                    <%= render 'layouts/calendar' , activities: @time_slots, week_number: 1, date_begin:
                        Date.today.beginning_of_week, show_toggle_button: false, show_date: true %>
                        <% if admin_signed_in? %>
                            <%= link_to "הכנס פעילות ללוח שנה" , new_time_slot_path(id: @activity.id),
                                class: "btn btn-primary" %>
                                <% if @activity.contract.nil? then path=new_contract_path(id: @activity.id) else
                                    path=edit_contract_path(id: @activity.id) end %>
                                    <%= link_to "עדכן חוזה" , path, class: "btn btn-primary" %>
                                        <% else %>
                                            <%= render 'layouts/contact_links' %>
                                                <%= link_to "חזרה לדף הבית" , root_path, class: "btn btn-primary" %>
                                                    <% end %>
                </div>
            </div>

    </div>